name: Build and Deploy NestJS App to Azure Web App - hushlearn

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'pnpm' # Enables caching for faster installs

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build NestJS application
        run: pnpm run build

      - name: Package for deployment
        run: |
          mkdir deploy
          cp -r dist package.json pnpm-lock.yaml node_modules deploy/
          zip -r release.zip deploy

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d deploy_dir

      - name: Ensure pnpm is available on Azure
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          export PATH=$HOME/.local/share/pnpm:$PATH

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hushlearn'
          slot-name: 'Production'
          package: './deploy_dir/deploy'  # Deploy only necessary files
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A138BA99775949BBAAB41320E968EA90 }}
